services:
  dev_prometheus_container_exporter:
    image: prometheus/container-exporter:dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
